package vistas;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.Venta;
import modelos.Detalle;
import modelos.Producto;

/**
 * @author Moisés
 */
public class FrmVenta extends javax.swing.JFrame {
    // Atributos para emular el manejo de una base de datos
    private ArrayList<Detalle> listaDetalle;
    private ArrayList<Venta> listaVenta;
    // --------------------------------------
    private LocalDate fecha;
    private String[] nombreColumnas;
    private DefaultTableModel tablaModelo;
    private int filaEliminar;
    
    // Constructor
    public FrmVenta() {
        fecha = LocalDate.now();
        listaDetalle = new ArrayList<>();
        listaVenta = new ArrayList<>();
        nombreColumnas = new String[] {"Item", "ID Producto", "Descripción", "Precio (S/.)", "Cantidad", "SubTotal (S/.)"};
	tablaModelo = new DefaultTableModel(nombreColumnas, 0);
        initComponents();
        filaEliminar = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        etiIdVenta = new javax.swing.JLabel();
        txtIdVenta = new javax.swing.JTextField();
        etiIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        btnBuscarIdCliente = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        etiNombre = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lineaSeparadora = new javax.swing.JSeparator();
        etiIdProducto = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnBuscarIdProducto = new javax.swing.JButton();
        etiPrecioProducto = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        etiCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        etiDescripcionProducto = new javax.swing.JLabel();
        txtDescripcionProducto = new javax.swing.JTextField();
        etiIgvVenta = new javax.swing.JLabel();
        txtIgvVenta = new javax.swing.JTextField();
        etiTotalVenta = new javax.swing.JLabel();
        txtTotalVenta = new javax.swing.JTextField();
        panelDesplazamiento = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de Ventas");

        etiFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiFecha.setText("Fecha:");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFecha.setText(fecha.toString().replaceAll("-", "/"));

        etiIdVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiIdVenta.setText("ID Venta:");

        txtIdVenta.setEditable(false);
        txtIdVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdVenta.setText("1");

        etiIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiIdCliente.setText("ID Cliente:");

        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdCliente.setText("0");

        btnBuscarIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarIdCliente.setText("Buscar");
        btnBuscarIdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarIdClienteMouseClicked(evt);
            }
        });

        btnNuevaVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaVentaMouseClicked(evt);
            }
        });

        etiNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiNombre.setText("Nombre:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        etiIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiIdProducto.setText("ID Producto:");

        txtIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdProducto.setText("0");

        btnBuscarIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarIdProducto.setText("Buscar");
        btnBuscarIdProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarIdProductoMouseClicked(evt);
            }
        });

        etiPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiPrecioProducto.setText("Precio:");

        txtPrecioProducto.setEditable(false);
        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioProducto.setText("0.00");

        etiCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiCantidad.setText("Cantidad:");

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidad.setText("0");

        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
        });

        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarProductoMouseClicked(evt);
            }
        });

        etiDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiDescripcionProducto.setText("Descripción:");

        txtDescripcionProducto.setEditable(false);
        txtDescripcionProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        etiIgvVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiIgvVenta.setText("IGV:");

        txtIgvVenta.setEditable(false);
        txtIgvVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIgvVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIgvVenta.setText("0.00");

        etiTotalVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiTotalVenta.setText("Total:");

        txtTotalVenta.setEditable(false);
        txtTotalVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalVenta.setText("0.00");

        tablaProductos.setModel(tablaModelo);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        // Definir el ancho para cada columna individualmente
        tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(40); // Columna "Num." Ancho: 40 píxeles
        tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(80); // Columna "ID Producto" Ancho: 80 píxeles
        tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(484); // Columna "Descripción" Ancho: 484 píxeles
        tablaProductos.getColumnModel().getColumn(3).setPreferredWidth(80); // Columna "Precio (S/.)" Ancho: 80 píxeles
        tablaProductos.getColumnModel().getColumn(4).setPreferredWidth(80); // Columna "Cantidad" Ancho: 80 píxeles
        tablaProductos.getColumnModel().getColumn(5).setPreferredWidth(180); // Columna "SubTotal (S/.)" Ancho: 180 píxeles
        panelDesplazamiento.setViewportView(tablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiDescripcionProducto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(etiIgvVenta)
                                .addGap(10, 10, 10)
                                .addComponent(txtIgvVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(etiTotalVenta)
                                .addGap(10, 10, 10)
                                .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lineaSeparadora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiIdCliente)
                                    .addComponent(etiFecha)
                                    .addComponent(etiNombre)
                                    .addComponent(etiIdProducto))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiPrecioProducto)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(etiCantidad)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDescripcionProducto)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(etiIdVenta)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnBuscarIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(panelDesplazamiento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiFecha)
                    .addComponent(etiIdVenta)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiIdCliente)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevaVenta)
                    .addComponent(btnBuscarIdCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiNombre)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lineaSeparadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiIdProducto)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiPrecioProducto)
                    .addComponent(btnAgregarProducto)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiCantidad)
                    .addComponent(btnBuscarIdProducto)
                    .addComponent(btnEliminarProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiDescripcionProducto)
                    .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelDesplazamiento, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiTotalVenta)
                    .addComponent(txtIgvVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiIgvVenta))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Busca al cliente por su ID y muestra los datos en las cajas de texto.
     */
    private void btnBuscarIdClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdClienteMouseClicked
        Cliente clienteBuscado = Cliente.buscarPorID(Integer.parseInt(txtIdCliente.getText()));
        txtCliente.setText(clienteBuscado.getNombre() + " - " + clienteBuscado.getDocumento());
    }//GEN-LAST:event_btnBuscarIdClienteMouseClicked

    /**
     * Busca al producto por su ID y muestra los datos en las cajas de texto.
     */
    private void btnBuscarIdProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdProductoMouseClicked
        Producto productoBuscado = Producto.buscarPorID(Integer.parseInt(txtIdProducto.getText()));
        txtDescripcionProducto.setText(productoBuscado.getDescripcion());
        txtPrecioProducto.setText(String.format("%.2f", productoBuscado.getPrecio()));
    }//GEN-LAST:event_btnBuscarIdProductoMouseClicked

    /**
     * Agrega nuevas filas a la tabla de productos.
     */
    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        Producto productoBuscado = Producto.buscarPorID(Integer.parseInt(txtIdProducto.getText()));
        Detalle detalle = new Detalle(1, Integer.parseInt(txtIdVenta.getText()), 
                        productoBuscado.getID(), Integer.parseInt(txtCantidad.getText()));
        listaDetalle.add(detalle);
        listar_Productos_Totales();
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    /**
     * Elimina la fila de la tabla de productos que fue seleccionada por el cursor.
     */
    private void btnEliminarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProductoMouseClicked
        listaDetalle.remove(filaEliminar);
        listar_Productos_Totales();
    }//GEN-LAST:event_btnEliminarProductoMouseClicked

    /**
     * Borra todos los espacios llenados por el usuario incluyendo la tabla.
     */
    private void btnNuevaVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaVentaMouseClicked
        Venta ventaRealizada = new Venta(Integer.valueOf(txtIdVenta.getText()), 
                        fecha, Integer.valueOf(txtIdCliente.getText()));
        listaVenta.add(ventaRealizada);
        fecha = LocalDate.now();
        txtIdVenta.setText(String.valueOf(ventaRealizada.getID() + 1));
        txtIdCliente.setText("0");
        txtCliente.setText("");
        txtIdProducto.setText("0");
        txtPrecioProducto.setText("0.00");
        txtCantidad.setText("0");
        txtDescripcionProducto.setText("");
        tablaModelo.setRowCount(0);
        listaDetalle.clear();
    }//GEN-LAST:event_btnNuevaVentaMouseClicked

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        filaEliminar = tablaProductos.getSelectedRow();
    }//GEN-LAST:event_tablaProductosMouseClicked

    // Métodos personalizados
    /**
     * Lista los detalles en la tabla de productos y calcula tanto el IGV como el total.
     */
    private void listar_Productos_Totales(){
        tablaModelo.setRowCount(0);
        int filas = 1; double total = 0.0, igv = 0.18;
        for (Detalle d : listaDetalle) {
            Producto prodB = Producto.buscarPorID(d.getID_Producto());
            tablaModelo.addRow(new Object[] {filas++, 
                                        prodB.getID(), 
                                        prodB.getDescripcion(), 
                                        String.format("%.2f", prodB.getPrecio()), 
                                        d.getCantidad(), 
                                        String.format("%.2f", d.subTotal())});
            total += d.subTotal();
        }
        igv *= total; total += igv;
        txtIgvVenta.setText(String.format("%.2f", igv));
        txtTotalVenta.setText(String.format("%.2f", total));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarIdCliente;
    private javax.swing.JButton btnBuscarIdProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JLabel etiCantidad;
    private javax.swing.JLabel etiDescripcionProducto;
    private javax.swing.JLabel etiFecha;
    private javax.swing.JLabel etiIdCliente;
    private javax.swing.JLabel etiIdProducto;
    private javax.swing.JLabel etiIdVenta;
    private javax.swing.JLabel etiIgvVenta;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiPrecioProducto;
    private javax.swing.JLabel etiTotalVenta;
    private javax.swing.JSeparator lineaSeparadora;
    private javax.swing.JScrollPane panelDesplazamiento;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtIgvVenta;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtTotalVenta;
    // End of variables declaration//GEN-END:variables
}
